from nginx
run rm -rf /usr/share/nginx/html/index.html
run rm -rf /etc/nginx/nginx.conf
run rm -rf /etc/nginx/conf.d/default.conf
copy roboshop.conf /etc/nginx/default.d/roboshop.conf
add static /usr/share/nginx/html/